Feature/Userstory1 - Create the price info and the list of bikes
YuriPadilla/capstone-project-havana-bikes pull request #6
Opened 2023-01-25 15:39 UTC by YuriPadilla

2023-01-26 08:28 UTC, doemser requested changes

2023-01-26 08:28 UTC, doemser commented on components/BikesList/index.js
> +              key={uuidv4()}
A key should not be generated right here while mapping, this would cause react to create a new id on every render. Any optimization that React makes through the keys will be invalidated. Just take the bike.id here.

2023-01-26 08:28 UTC, doemser commented on components/BikesList/index.js
> +              alt={bike.marke}
here you mix german with english terms. Try to avoid that.

2023-01-26 08:28 UTC, doemser commented on components/BikesPreview/index.js
> +  });
```suggestion
const bikesForPreview = bikes.slice(0, 4);
```

2023-01-26 08:28 UTC, doemser commented on components/BikesPreview/index.js
> +        </div>
Do you need this wrapping div?

2023-01-26 08:28 UTC, doemser commented on components/BikesPreview/index.js
> +                key={uuidv4()}
don't generate key while mapping.

2023-01-26 08:29 UTC, Long-HaHoang requested changes
Overall a good structure.
There are some minor issues, here and there.
It's really readable and clean.

2023-01-26 08:29 UTC, Long-HaHoang commented on components/Header/index.js
> +      </h3>
You can use a `<h1>` here instead of a `<h3>`
The h1 is your main heading and you only have one `StyledHeader`

2023-01-26 08:29 UTC, Long-HaHoang commented on components/PriceInfo/index.js
> +      <h2>Lease Time & Price</h2>
Your can move the `h2` inside of the section

2023-01-26 08:29 UTC, Long-HaHoang commented on components/PriceInfo/index.js
> +      </section>
This part is not really semantic.
In your case can turn the `div` into a `article`
And the `article` into a `p`

2023-01-26 08:29 UTC, Long-HaHoang commented on pages/index.js
> +        <Link href="">Home</Link>
I guess you got the routing reversed.
`pages/index.js` this is your Homepage/Landing Page.

2023-01-26 08:29 UTC, Long-HaHoang commented on pages/Bikes/index.js
> +        <Link href="/">Home</Link>→<Link href="">Bikes</Link>
You can't navigate from the Homepage to this site, since there is no link to `pages/Bikes`

2023-01-26 13:42 UTC, NikRoe requested changes
Hey Yuri,
looks good overall, however, there are some comments left you can remove and there is some feedback from Long regarding two of your links you should look into.

2023-01-26 13:42 UTC, NikRoe commented on components/BikesList/index.js
> +//import { v4 as uuidv4 } from "uuid";
you can remove this line of code

2023-01-26 13:42 UTC, NikRoe commented on components/BikesPreview/index.js
> +//import { v4 as uuidv4 } from "uuid";
you can remove this line of code

2023-01-26 13:42 UTC, NikRoe commented on components/Header/StyledHeader.styled.js
> +import styled, { css } from "styled-components";
do you need to import `{css}` here?

```suggestion
import styled from "styled-components";
```

2023-01-26 13:42 UTC, NikRoe commented on components/Header/StyledHeader.styled.js
> +*/
you can remove this comment

2023-01-26 15:15 UTC, NikRoe approved these changes
Hey Yuri,

looks good!

I think there is one import you don't need, nothing mayor, though

2023-01-27 10:23 UTC, AGeck113 approved these changes

2023-01-27 10:23 UTC, AGeck113 commented on components/PriceInfo/index.js
> +      <h2>Lease Time & Price</h2>
Did you do that? I can't see it here un github.

2023-01-27 10:23 UTC, AGeck113 commented on pages/Bikes/index.js
> +      </p>
Do you need to nest the Link inside the p tag? Just a comment.

2023-01-27 10:35 UTC, YuriPadilla commented on pages/Bikes/index.js
> +      </p>
Yes, because only "Home" hat the nested link and "Bikes" don't (<p>Home→Bikes</p>)
Thanks Andreas!!!  :)

2023-01-27 13:46 UTC, merged