User Story 2 - Add contact info
YuriPadilla/capstone-project-havana-bikes pull request #7
Opened 2023-01-27 14:08 UTC by YuriPadilla

2023-01-27 15:09 UTC, F-Kirchhoff requested changes
Hey Yuri, 
besides the CSS issues and the Links disguised as buttons you are ready to go. Good work!

2023-01-27 15:09 UTC, F-Kirchhoff commented on components/ContactInfo/index.js
> +        </StyledButton>
please use the next Link component for this usecase instead. This is better for folks who use screenreaders. You don't need the router hook then.

2023-01-27 15:09 UTC, F-Kirchhoff commented on components/ContactInfo/index.js
> +          <article>Land line: (+53) 7 867 6782</article>
These are not articles, but either spans or p tags.

2023-01-27 15:09 UTC, F-Kirchhoff commented on components/ContactUsForm/index.js
> +          </StyledButton>
Same here.

2023-01-27 15:09 UTC, F-Kirchhoff commented on components/ContactUsForm/index.js
> +        </label>
Please don't nest the input in the label. Screen readers read all the content of the Label tag, also html. That is pretty annoying if the input tag is read out to you every time you use the form. You already have a htmlFor property and an id, so you can simply move the input next to its label.

2023-01-27 15:09 UTC, F-Kirchhoff commented on components/ContactUsForm/index.js
> +          <br />
please remove these br tags and use CSS to create a gap between the elements.

2023-01-27 15:09 UTC, F-Kirchhoff commented on components/ToastNotification/index.js
> +    <button className={`toast ${toastAction}`}>Your message was sent</button>
Please don' use class names alongside with styled Components. We write the CSS purely in styled components.

2023-01-27 15:09 UTC, F-Kirchhoff commented on components/ToastNotification/index.js
> +    <button className={`toast ${toastAction}`}>Your message was sent</button>
you can pass props to your styled component to achieve the same as you do with the toastAction

2023-01-27 15:09 UTC, F-Kirchhoff commented on pages/ContactUsPage/index.js
> +    console.log(data);
remove all console.logs before pushing 🕵️

2023-01-27 15:09 UTC, F-Kirchhoff commented on styles/styles.css
> +}
you need to solve this with styled components. You can use toastAction as a prop inside your ToastNotification styled Component to add different stylings.

2023-01-28 19:30 UTC, Long-HaHoang requested changes
Hi Yuri,
Your links are still inside of buttons.
And your input fields need some validations.

2023-01-28 19:30 UTC, Long-HaHoang commented on pages/index.js
>        <p>Home</p>
What's the point of this paragraph?
Do you really need to tell the user, that this is the home page?
It's already your landing page.
Besides if you want to keep it I suggest you to use a `<h2>` here.

2023-01-28 19:30 UTC, Long-HaHoang commented on pages/ContactUsPage/index.js
> +      </p>
Now you have two ways on same page to move back to the home page.
Besides that, you already have a heading for "Contact us" in your form.

2023-01-29 17:24 UTC, YuriPadilla commented on components/ContactUsForm/index.js
> +      <label htmlFor="message">*Message:</label>
Hi Long!
Well... yes, I just wanted to indicate the user that this input is required.

2023-01-29 19:58 UTC, YuriPadilla commented on components/ContactUsForm/index.js
> +      <input type="text" id="name" name="name" required />
A pattern to the name... maybe later...

2023-01-29 20:04 UTC, YuriPadilla commented on pages/index.js
>        <p>Home</p>
The point is to fallow the same pattern as in other pages... and I use it to show the history of the links. A `<h2>` is not properly here.

2023-01-29 20:05 UTC, YuriPadilla commented on pages/index.js
>        <p>Home</p>
I think it is properly to keep it.

2023-01-29 20:09 UTC, YuriPadilla commented on pages/ContactUsPage/index.js
> +      </p>
I think it's OK so...

2023-01-29 20:13 UTC, YuriPadilla commented on components/ContactInfo/index.js
> +        </StyledButton>
Good Idea, Thanks!!!  :)

2023-01-29 20:15 UTC, YuriPadilla commented on components/ContactUsForm/index.js
> +      />
You are right! ...I thought I had it required.

2023-01-30 09:15 UTC, YuriPadilla commented
Thank you Long-HaHoang and F-Kirchhoff for reviewing my code!!!!! it was really helpful. Hope to get more reviews from you all...!!!

2023-01-31 10:25 UTC, merged