Feature/userstory4
YuriPadilla/capstone-project-havana-bikes pull request #9
Opened 2023-02-01 10:14 UTC by YuriPadilla

2023-02-01 11:29 UTC, marcterre requested changes
Please have a look at my comments 🙂
Nice short PR!

2023-02-01 11:29 UTC, marcterre commented on components/BikesList/index.js
>        </div>
If you want to map over a list, consider using list-tags. You can write it like that:
```js
<ul>
   {bikes.map((bike) => (
      <li key={bike.id}>
         <Image/>
            <Link> Whatever </Link>
      </li>
    ))
}
</ul>
```

2023-02-01 11:29 UTC, marcterre commented on components/BikesList/index.js
>        </div>
If you have questions about that, dont mind asking me 🙂

2023-02-01 11:29 UTC, marcterre commented on components/ProductDetails/index.js
> +        </article>
You can also put this in a list, at least dont use one ```p``` for Mark and Size.
Here is an example:
instead of ```article``` use ```ul```
```js
<ul>
   <li><strong>Mark:</strong>.....</li>
   <li><strong>Size:</strong>......</li>
</ul>
```

2023-02-01 11:29 UTC, marcterre commented on pages/Bikes/[id].js
> +      <ProductDetails product={currentBike} />
If you use a Header maybe wrap a ```main```around this section, also i dont think its necessary to wrap ```p``` around your Links. If you need it for styling use ```div```

There are characters between your Link-tags which you shouldnt use like that. They should be wrapped in tags, like ```div``` if you want to style your Links with it

2023-02-01 11:51 UTC, YuriPadilla commented on components/BikesList/index.js
>        </div>
Hey Marc! Thank you for reviewing my code.  :)
About this, I want to have the bikes images in a `<div>`. I don't want a `<ul>` list for it, I don't think it is properly to display it in a `<ul>`.
That's why I think it is properly to let the `<div>` in this case.

2023-02-01 11:55 UTC, YuriPadilla commented on components/ProductDetails/index.js
> +        </article>
That could be. I take it... it is a good idea. Thanks!

2023-02-01 12:18 UTC, YuriPadilla commented on pages/Bikes/[id].js
> +      <ProductDetails product={currentBike} />
I think the `<main>` is a good idea. I will do it. Thanks!!!   :)

2023-02-01 12:19 UTC, YuriPadilla commented on pages/Bikes/[id].js
> +      <ProductDetails product={currentBike} />
About `<p>`I think that's necessary because the "→Details" is out of the link and the `<p>` takes all together.

2023-02-01 12:21 UTC, YuriPadilla commented on pages/Bikes/[id].js
> +      <ProductDetails product={currentBike} />
About the `<div>`, I could use it later in case I decide to style the links.

2023-02-01 15:11 UTC, F-Kirchhoff requested changes
Hey Yuri, please add a layout wrapper in your _app.js as described below. Also you need to wrap your Links in a ul/li structure. Besides that your code looks great!

2023-02-01 15:11 UTC, F-Kirchhoff commented on components/BikesList/index.js
>        </div>
Hey Yuri, Marc is right here, If your component is semantially a list (and it is, you even named it a List), then you need to use an ul as the container element. Each child must be a li element then. You can always use styled-components to change the display of that list. Best way is to wrap each Link in a li element, apply the key prop to that li element and change the div into a ul.

2023-02-01 15:11 UTC, F-Kirchhoff commented on components/ProductDetails/index.js
> +              <strong>Mark:</strong> {product.mark}
the correct name is "brand" instead of Mark. Please change it in the strong tag as well as in your data.

2023-02-01 15:11 UTC, F-Kirchhoff commented on pages/BikeParts/index.js
>        <Header />
It looks like you add the Header in each page. Please create a Layout component which wraps the "Component" in the _app.js. In this Layout component, render the Header, as well as the "children" prop underneath it.

2023-02-01 15:11 UTC, F-Kirchhoff commented on pages/BikeParts/index.js
>        <Header />
The goal is to specify the Header component only once in the page layout instead of defining it in each page reparately.

2023-02-01 17:23 UTC, YuriPadilla commented on pages/BikeParts/index.js
>        <Header />
Super, it is a very good tipp!!! I've already done it.
Thank you!!!   :)

2023-02-01 17:24 UTC, YuriPadilla commented on components/ProductDetails/index.js
> +              <strong>Mark:</strong> {product.mark}
I've just done it. Thanks!!!

2023-02-01 17:29 UTC, YuriPadilla commented
Thank you Marc!!! Thank you Felix!!! Your reviews were really helpful...!!!

Hope to get more reviews from you guys. Many greetings!!!  😀  👍

2023-02-01 22:29 UTC, AstridOttmann commented on components/BikePartsPreview/BikePartsPreview.styled.js
> +`;
Hey Yuri, 
later on you define styles for ul and li again. Maybe you can put this together in one file using a variant-syntax for styled components. 
`${({variant}) => variant === 'bikeParts' && css`
   ... css here
`}
${({variant}) => variant === 'bikePartsPreview' && css`
   ... css here
`}`

2023-02-01 22:38 UTC, AstridOttmann commented on pages/Bikes/[id].js
> +      <ProductDetails product={currentBike} />
I also think the <p> is not a good practice to wrap a link. 
But apart from that your. code looks really good now!

2023-02-02 11:23 UTC, AstridOttmann approved these changes

2023-02-02 11:47 UTC, YuriPadilla commented
Thanks Astrid!!! 😀 👍

2023-02-02 13:42 UTC, merged

2023-02-06 09:42 UTC, YuriPadilla commented on components/BikePartsPreview/BikePartsPreview.styled.js
> +`;
I like it, Thanks  :)